### ISSUE TITLE
Move /log code into `POST /users/login`

### ISSUE THREAD

**Issue by ecumene** [TDrake38/tool-swappin#76]
Replace this

https://github.com/TDrake38/tool-swappin/blob/b71f193520eff8917db01137e60226f2e07036a3/backend/src/Server.js#L53

With this:

https://github.com/TDrake38/tool-swappin/blob/b71f193520eff8917db01137e60226f2e07036a3/backend/src/Server.js#L82

**Comment by TDrake38** [comment]
Complete
