### ISSUE TITLE
This should use `req.user.id` not `req.body.senderID`

### ISSUE THREAD

**Issue by ecumene** [TDrake38/tool-swappin#88]
https://github.com/TDrake38/tool-swappin/blob/d58cb662fc72d8c097833d9bbcd458b8873f830d/backend/src/controllers/messages.controller.js#L22

**Comment by ecumene** [comment]
This too! https://github.com/TDrake38/tool-swappin/blob/d58cb662fc72d8c097833d9bbcd458b8873f830d/backend/src/controllers/messages.controller.js#L10

**Comment by TDrake38** [comment]
Complete
